version: "3"
services:
  geth-node:
    container_name: geth-node
    image: "ethereum/client-go"
    entrypoint:
      - '/bin/sh'
    command: '/usr/src/nodestart'
    environment:
      - WORKDIR=/usr/src/
    volumes:
      - ".:/usr/src"
    ports:
      - "8545:8545"
      - "8546:8546"
